services:
  primary:
    image: redis:7.4@sha256:a8f08480e1f88f2647fed492d1178c06abb0d0c1fbf02c682a61e2f483fb3954
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --enable-debug-command
      - "yes"
    ports:
      - "127.0.0.1:6391:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  replica:
    image: redis:7.4@sha256:a8f08480e1f88f2647fed492d1178c06abb0d0c1fbf02c682a61e2f483fb3954
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --enable-debug-command
      - "yes"
      - --replicaof
      - primary
      - "6379"
      - --replica-read-only
      - "yes"
    depends_on:
      primary:
        condition: service_healthy
    ports:
      - "127.0.0.1:6392:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
