# Site settings
title: akisonlyforu
email: kumaravinashinbox@gmail.com
description: >- 
  Write an awesome description for your blog here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-113168316-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
show_related_posts: True
show_post_footers: True
show_subscribe_cta: True
show_social_icons: true
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: akisonlyforu
twitter_username: akisonlyforu
linkedin_username: akisonlyforu

text:
  pagination:
    newer: "Newer"
    older: "Older"
  post:
    updated: "Updated"
    minute_read: "minute read"
    related_posts: "More to read"
  index:
    coming_soon: "Coming soon..."
  og_locale: "en_US"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data", "footnotes"]
permalink: /blog/:title/
paginate: 12
paginate_path: "/blog/:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - README.md

collections_dir: collections
collections:
  portfolio:
    output: true
  posts: {}

# Form settings
formspree_id: xeoaoopl  # Get this from formspree.io after creating a form

# Substack settings
substack_home_url: https://akisonlyforu.substack.com