services:
  redis-je:
    build:
      context: .
      args:
        MALLOC: jemalloc
        REDIS_VERSION: 7.4.0
        REDIS_SHA256: 74effebe3d0e3ac582f5248492c13e7ca4918949b58b45873d37fc870a4b1fc6
    container_name: redis-jemalloc-je
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --maxmemory
      - "1gb"
      - --maxmemory-policy
      - noeviction
      - --activedefrag
      - "no"
      - --protected-mode
      - "no"
    ports:
      - "127.0.0.1:56380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  redis-lc:
    build:
      context: .
      args:
        MALLOC: libc
        REDIS_VERSION: 7.4.0
        REDIS_SHA256: 74effebe3d0e3ac582f5248492c13e7ca4918949b58b45873d37fc870a4b1fc6
    container_name: redis-jemalloc-libc
    command:
      - redis-server
      - --save
      - ""
      - --appendonly
      - "no"
      - --maxmemory
      - "1gb"
      - --maxmemory-policy
      - noeviction
      - --activedefrag
      - "no"
      - --protected-mode
      - "no"
    ports:
      - "127.0.0.1:56381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
