services:
  redis:
    image: redis/redis-stack-server:latest@sha256:798ab84d9f266936b034ab11c4d04a2b8e4b441884c5aa7d17ac951eefdf742a
    command:
      - redis-stack-server
      - --save
      - ""
      - --appendonly
      - "no"
    ports:
      - "127.0.0.1:6399:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
