receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64

processors:
  tail_sampling:
    decision_wait: ${env:DECISION_WAIT}
    num_traces: ${env:NUM_TRACES}
    expected_new_traces_per_sec: ${env:EXPECTED_NEW_TPS}
    policies:
      - name: keep-errors
        type: status_code
        status_code:
          status_codes: [ERROR]
      - name: keep-slow
        type: latency
        latency:
          threshold_ms: ${env:LATENCY_THRESHOLD_MS}

exporters:
  debug:
    verbosity: basic

service:
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [debug]
